### ISSUE TITLE
test if simdeep is functional 

### ISSUE THREAD

**Issue by luhan125** [lanagarmire/DeepProg#9]
Hi，
When I used the test file for python examples/example_with_dummy_data.py, the errors were:

model with random state:952 didn't converge:'NoneType' object is not callable
Results: [False, False, False, False, False]
0 models fitted
Traceback (most recent call last):
  File "/home/liuzh/software/DeepProg/examples/example_with_dummy_data.py", line 122, in <module>
    test_instance()
  File "/home/liuzh/software/DeepProg/examples/example_with_dummy_data.py", line 72, in test_instance
    boosting.fit()
  File "/home/liuzh/software/DeepProg/simdeep/simdeep_boosting.py", line 482, in fit
    self._fit(
  File "/home/liuzh/software/DeepProg/simdeep/simdeep_boosting.py", line 624, in _fit
    raise e
  File "/home/liuzh/software/DeepProg/simdeep/simdeep_boosting.py", line 620, in _fit
    assert(nb_models)
AssertionError

How can I solve this error? I am looking forward for your reply.

Thank you a lot!

**Comment by opoirion** [comment]
Hello and thank you very much for your interest in our work!

It is not normal that the example dummy models are not converging. In the example, I realized that the option use_R_package was set to true, which might cause this error. I also updated the example script. Otherwise, it might also be a dependency issue if you didn't installed the exact same version of sklearn,seaborn, ray,...etc... because the API of these packages evolves fast. I would recoomand to use the docker / singularity container
